title: 宇浩输入法·繁简通
description: 繁简通打·极致低重·全汉字输入
theme: just-the-docs

url: https://zhuyuhao.com/yuhao/

aux_links:
  点击加入QQ群: https://jq.qq.com/?_wv=1027&k=2OYDP4Tk
  点击加入Telegram群: https://t.me/yuhaoim

# External navigation links
nav_external_links:
  - title: 拆分查询·二代
    url: https://zhuyuhao.com/yuhao/v2/chaifen
    hide_icon: false # set to true to hide the external link icon - defaults to false
  - title: 拆分查询·一代
    url: https://zhuyuhao.com/yuhao/v1/chaifen
    hide_icon: false # set to true to hide the external link icon - defaults to false
  # - title: 玫枫跟打器
  #   url: https://kylebing.cn/tools/typepad/
  #   hide_icon: false # set to true to hide the external link icon - defaults to false
  # - title: 内置宇浩的iOS仓输入法
  #   url: https://apps.apple.com/us/app/%E4%BB%93%E8%BE%93%E5%85%A5%E6%B3%95/id6446617683
  #   hide_icon: false # set to true to hide the external link icon - defaults to false

markdown: kramdown
math: katex
layout: katex

# kramdown:
#   syntax_highlighter_opts:
#     block:
#       line_numbers: false

callouts:
  highlight:
    color: yellow
  important:
    title: 重要
    color: blue
  example:
    # title: 举例
    color: green
  note:
    title: 备注
    color: purple
  warning:
    title: 提醒
    color: red